export const SITE = {
  website: "https://blog.amansharma.cv",
  author: "Aman Sharma",
  profile: "https://amansharma.cv",
  desc: "Backend engineering blog covering systems, security, authentication, and distributed systems.",
  title: "Aman Sharma",
  ogImage: "og-image.jpg", 
  lightAndDarkMode: true,
  postPerIndex: 5,
  postPerPage: 5,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit on GitHub",
    url: "https://github.com/gsamansharma/blog/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Asia/Kolkata",
} as const;
