export const SITE = {
  website: "https://blog.amansharma.cv",
  author: "Aman Sharma",
  profile: "https://amansharma.cv",
  desc: "Aman Sharma's blog dives into backend engineering, security, authentication, and distributed systems with practical insights.",
  title: "Aman Sharma blogs",
  ogImage: "og-image.jpg",
  lightAndDarkMode: true,
  postPerIndex: 5,
  postPerPage: 5,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: {
    enabled: false,
    text: "Edit on GitHub",
    url: "https://github.com/gsamansharma/blog/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "en",
  timezone: "Asia/Kolkata",
  analytics: {
    umamiId: "565498fa-f355-4693-a4ca-a6e56abcc68f",
  },
} as const;
